"""
Admin user-management service — Phase 4 PR #13.

Pure DB I/O for the ``/v1/admin/users/*`` HTTP surface. The router is a thin
adapter that translates HTTP shapes into these calls and turns the domain
exceptions below into RFC 7807 responses.

Safety contracts (CLAUDE.md "조직/팀/권한 모델" + PR #13 spec §4.2):
  - Demoting / deactivating the *last* active super_admin is rejected.
    422 with extension ``last_super_admin_protected = true``.
  - The actor cannot mutate their own role / activation state — there is
    no recovery path if the only super_admin locks themselves out.
    422 with extension ``cannot_modify_self = true``.
  - Password-reset tokens are bcrypt-hashed; the plaintext is generated by
    the issuer endpoint and intentionally discarded after issuance. Phase 6
    PR #18 wires the email channel that delivers the plaintext.
  - Single-pending-token policy: issuing a new reset token marks any
    previous unused / non-expired / non-invalidated rows for the same user
    as ``invalidated_at = now()``.

Audit hand-off:
  Mutating ORM rows is enough — the SQLAlchemy ``before_flush`` listener
  in ``core.audit`` produces the audit_logs row automatically. Sensitive
  columns (``hashed_password``, ``token_hash``) are auto-masked in the diff.
  Service code therefore must never call ``session.add(AuditLog(...))``.
"""

from __future__ import annotations

import secrets
import uuid
from datetime import UTC, datetime, timedelta

import structlog
from sqlalchemy import func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from core.security import CurrentUser, hash_password
from models import Membership, PasswordResetToken, RefreshToken, Scan, Team, User
from schemas.admin import (
    AdminUserDetail,
    AdminUserListItem,
    AdminUserListPage,
    AdminUserRoleUpdate,
    TeamMembershipPublic,
)

log = structlog.get_logger("admin.user.service")


# ---------------------------------------------------------------------------
# Domain exceptions
# ---------------------------------------------------------------------------


class AdminUserError(Exception):
    """Base class for admin-user errors. Each carries an HTTP status."""

    status_code: int = 400
    title: str = "Admin User Error"
    extensions: dict[str, object] = {}


class AdminUserNotFound(AdminUserError):
    status_code = 404
    title = "User Not Found"


class LastSuperAdminProtected(AdminUserError):
    status_code = 422
    title = "Last Super Admin Protected"
    extensions = {"last_super_admin_protected": True}


class CannotModifySelf(AdminUserError):
    status_code = 422
    title = "Cannot Modify Self"
    extensions = {"cannot_modify_self": True}


class InvalidRoleAssignment(AdminUserError):
    status_code = 422
    title = "Invalid Role Assignment"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _now() -> datetime:
    return datetime.now(tz=UTC)


async def _lock_and_count_active_super_admins(session: AsyncSession) -> int:
    """
    Acquire a row-level lock on the active-super-admin set and return the count.

    Closes the TOCTOU race between SELECT-then-mutate that a plain
    ``SELECT count()`` would expose: two concurrent demote/deactivate
    transactions could each read ``count == 2``, both pass the ``> 1`` guard,
    and then both commit, dropping the active super_admin count to zero.

    The locking SELECT pulls every (is_active, is_superuser) row with
    ``FOR UPDATE``. Postgres holds those row locks until the calling
    transaction commits or rolls back — so a second concurrent call against
    any of the same rows blocks until the first finishes, at which point
    the second sees the post-commit count and the guard fires correctly.

    Lock order convention (also documented in admin_team_service):
      ``users (is_superuser=true AND is_active=true)`` is always locked
    BEFORE any ``memberships`` rows in the same transaction, to keep a
    consistent global lock order across the two admin services and avoid
    deadlocks on cross-service operations.

    Reference: feedback_optimistic_concurrency_pattern memory; pattern
    matches ``vulnerability_service.py:309`` (``with_for_update`` on the
    finding row before the optimistic-concurrency compare-and-swap).
    """
    # Pull the rows with FOR UPDATE so Postgres takes the row locks. We
    # then count from the materialized list — using a separate
    # ``SELECT count()`` would emit a second statement that does NOT take
    # the same locks. ``scalars().all()`` consumes the result and forces
    # the lock to be acquired.
    locked = (
        (
            await session.execute(
                select(User)
                .where(User.is_active.is_(True), User.is_superuser.is_(True))
                .with_for_update()
            )
        )
        .scalars()
        .all()
    )
    return len(locked)


async def _load_user_with_memberships(session: AsyncSession, user_id: uuid.UUID) -> User:
    """
    Fetch the user with its memberships eagerly loaded.

    If the User is already in the session's identity map (likely after a
    prior mutation in this same call chain), we refresh the memberships
    collection explicitly so the response sees the post-commit state.
    Without this step a User that was loaded earlier — e.g. in
    update_user_role before we added a Membership row — would be served
    from the identity map with a stale empty memberships collection.
    """
    stmt = select(User).where(User.id == user_id).options(selectinload(User.memberships))
    user = (await session.execute(stmt)).scalar_one_or_none()
    if user is None:
        raise AdminUserNotFound(f"user {user_id} not found")
    # Even though the SELECT requested memberships eagerly, SQLAlchemy may
    # serve the User from the identity map; an explicit refresh of the
    # collection guarantees we see fresh rows from any prior commit in
    # this session.
    await session.refresh(user, attribute_names=["memberships"])
    return user


async def _team_name_map(session: AsyncSession, team_ids: list[uuid.UUID]) -> dict[uuid.UUID, str]:
    if not team_ids:
        return {}
    stmt = select(Team.id, Team.name).where(Team.id.in_(team_ids))
    rows = (await session.execute(stmt)).all()
    return {row[0]: row[1] for row in rows}


async def _scan_count_for_user(session: AsyncSession, user_id: uuid.UUID) -> int:
    stmt = select(func.count()).select_from(Scan).where(Scan.requested_by_user_id == user_id)
    return int((await session.execute(stmt)).scalar_one())


# ---------------------------------------------------------------------------
# List
# ---------------------------------------------------------------------------


async def list_users(
    session: AsyncSession,
    *,
    actor: CurrentUser,  # noqa: ARG001 — kept for symmetry with other admin services
    page: int = 1,
    page_size: int = 50,
    role: str | None = None,
    active: bool | None = None,
    search: str | None = None,
) -> AdminUserListPage:
    """
    Return a page of users (paginated, filterable).

    - ``role`` filters by highest-effective role (super_admin = is_superuser;
      team_admin / developer = exists membership with that role; the filter
      is a coarse "user has at least one membership of this kind"). When
      role is ``super_admin`` we filter on ``is_superuser=true`` directly.
    - ``active`` filters by ``is_active`` exactly.
    - ``search`` is bounded substring ILIKE on email or full_name (max 255
      chars to bound the query cost).
    """
    page = max(page, 1)
    page_size = max(min(page_size, 200), 1)

    base = select(User)
    count_base = select(func.count()).select_from(User)

    if active is not None:
        base = base.where(User.is_active.is_(active))
        count_base = count_base.where(User.is_active.is_(active))

    if role == "super_admin":
        base = base.where(User.is_superuser.is_(True))
        count_base = count_base.where(User.is_superuser.is_(True))
    elif role in ("team_admin", "developer"):
        sub = select(Membership.user_id).where(Membership.role == role).scalar_subquery()
        base = base.where(User.id.in_(sub))
        count_base = count_base.where(User.id.in_(sub))

    if search:
        # Bounded substring search; the inputs are already capped at 255 in
        # the route layer (Query(max_length=255)). Search is intentionally
        # case-insensitive on email (CITEXT-friendly) and full_name.
        like = f"%{search.strip()}%"
        base = base.where(or_(User.email.ilike(like), User.full_name.ilike(like)))
        count_base = count_base.where(or_(User.email.ilike(like), User.full_name.ilike(like)))

    total = int((await session.execute(count_base)).scalar_one())

    rows_stmt = (
        base.order_by(User.created_at.desc(), User.id.desc())
        .limit(page_size)
        .offset((page - 1) * page_size)
    )
    rows = list((await session.execute(rows_stmt)).scalars().all())

    return AdminUserListPage(
        items=[AdminUserListItem.model_validate(u) for u in rows],
        total=total,
        page=page,
        page_size=page_size,
    )


# ---------------------------------------------------------------------------
# Get detail
# ---------------------------------------------------------------------------


async def get_user_detail(
    session: AsyncSession,
    *,
    actor: CurrentUser,  # noqa: ARG001
    user_id: uuid.UUID,
) -> AdminUserDetail:
    user = await _load_user_with_memberships(session, user_id)

    memberships = list(user.memberships)
    team_names = await _team_name_map(session, [m.team_id for m in memberships])
    scan_count = await _scan_count_for_user(session, user_id)

    return AdminUserDetail(
        id=user.id,
        email=user.email,
        full_name=user.full_name,
        is_active=user.is_active,
        is_superuser=user.is_superuser,
        last_login_at=user.last_login_at,
        created_at=user.created_at,
        updated_at=user.updated_at,
        scan_count=scan_count,
        memberships=[
            TeamMembershipPublic(
                team_id=m.team_id,
                team_name=team_names.get(m.team_id, ""),
                role=m.role,
            )
            for m in memberships
        ],
    )


# ---------------------------------------------------------------------------
# Update role
# ---------------------------------------------------------------------------


async def update_user_role(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_id: uuid.UUID,
    payload: AdminUserRoleUpdate,
) -> AdminUserDetail:
    """
    Set the user's role.

    Semantics:
      - ``role == "super_admin"`` -> ``user.is_superuser = True``. Existing
        memberships are not touched (the super_admin role is global; team
        memberships are independent).
      - ``role in {"team_admin", "developer"}`` -> ``user.is_superuser = False``
        AND upsert ``Membership(user_id, team_id, role)``. ``team_id`` is
        required.

    Safety: rejects (422) when the change would demote the last active
    super_admin or when the actor is the target user.
    """
    if user_id == actor.id:
        raise CannotModifySelf("cannot modify your own role")

    user = await _load_user_with_memberships(session, user_id)

    target_role = payload.role
    target_team_id = payload.team_id

    if target_role == "super_admin":
        # Promotion to super_admin (or no-op if already super_admin).
        user.is_superuser = True
        user.updated_at = _now()
    else:
        if target_team_id is None:
            raise InvalidRoleAssignment("team_id is required when role is team_admin or developer")

        # If we are demoting *from* super_admin, make sure we are not
        # removing the last lockout-prevention seat. Take a row-level lock
        # on the entire active-super-admin set BEFORE the count check so
        # two concurrent demote requests serialize through Postgres
        # instead of both passing an optimistic ``count > 1`` check
        # (CWE-367 TOCTOU; see _lock_and_count_active_super_admins).
        if user.is_superuser:
            count = await _lock_and_count_active_super_admins(session)
            # The user being demoted is counted; demoting them takes the
            # count to (count - 1). Reject when that would hit zero.
            if user.is_active and count <= 1:
                raise LastSuperAdminProtected("cannot demote the last active super_admin")
            user.is_superuser = False

        # Upsert the membership row.
        existing = next(
            (m for m in user.memberships if m.team_id == target_team_id),
            None,
        )
        if existing is None:
            session.add(
                Membership(
                    user_id=user.id,
                    team_id=target_team_id,
                    role=target_role,
                )
            )
        else:
            existing.role = target_role
            existing.updated_at = _now()

        user.updated_at = _now()

    await session.commit()
    # Expire so the refetch in get_user_detail picks up the new membership
    # row instead of serving the User from the identity map (which may have
    # been loaded without a memberships join).
    log.info(
        "admin.user.role_changed",
        actor_id=str(actor.id),
        target_user_id=str(user_id),
        new_role=target_role,
        team_id=str(target_team_id) if target_team_id else None,
    )

    # Reload with memberships for the response.
    return await get_user_detail(session, actor=actor, user_id=user_id)


# ---------------------------------------------------------------------------
# Activate / deactivate
# ---------------------------------------------------------------------------


async def deactivate_user(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_id: uuid.UUID,
) -> AdminUserDetail:
    """
    Set ``is_active = False`` and revoke every live refresh token.

    Safety:
      - Cannot deactivate self (cannot_modify_self=true).
      - Cannot deactivate the last active super_admin (last_super_admin_protected=true).
    """
    if user_id == actor.id:
        raise CannotModifySelf("cannot deactivate yourself")

    user = await _load_user_with_memberships(session, user_id)
    if not user.is_active:
        # Already deactivated — idempotent no-op. Still emit the detail.
        return await get_user_detail(session, actor=actor, user_id=user_id)

    if user.is_superuser:
        # Lock the active-super-admin row set inside this transaction
        # before the count check so two concurrent deactivations cannot
        # both pass the ``count > 1`` guard. CWE-367 TOCTOU fix.
        count = await _lock_and_count_active_super_admins(session)
        if count <= 1:
            raise LastSuperAdminProtected("cannot deactivate the last active super_admin")

    now = _now()
    user.is_active = False
    user.updated_at = now

    # Revoke every live refresh token so the deactivated user can no longer
    # rotate even if they hold a fresh refresh cookie. We pull live rows and
    # mutate them so the audit listener captures each revocation.
    live_tokens = (
        (
            await session.execute(
                select(RefreshToken).where(
                    RefreshToken.user_id == user_id,
                    RefreshToken.revoked_at.is_(None),
                )
            )
        )
        .scalars()
        .all()
    )
    for token in live_tokens:
        token.revoked_at = now
        token.revoked_reason = "logout"

    await session.commit()
    log.info(
        "admin.user.deactivated",
        actor_id=str(actor.id),
        target_user_id=str(user_id),
        revoked_token_count=len(live_tokens),
    )

    return await get_user_detail(session, actor=actor, user_id=user_id)


async def activate_user(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_id: uuid.UUID,
) -> AdminUserDetail:
    """Set ``is_active = True``. Idempotent on already-active users."""
    user = await _load_user_with_memberships(session, user_id)
    if user.is_active:
        return await get_user_detail(session, actor=actor, user_id=user_id)

    user.is_active = True
    user.updated_at = _now()
    await session.commit()
    log.info(
        "admin.user.activated",
        actor_id=str(actor.id),
        target_user_id=str(user_id),
    )
    return await get_user_detail(session, actor=actor, user_id=user_id)


# ---------------------------------------------------------------------------
# Password reset
# ---------------------------------------------------------------------------


# Hard-coded TTL for now. Phase 6 PR #18 may make this env-driven once the
# email channel ships. CLAUDE.md core rule #11 forbids reading env vars at
# module import time, so when that change happens it will move to a runtime
# `os.getenv()` inside this function.
_PASSWORD_RESET_TTL = timedelta(hours=1)


async def initiate_password_reset(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_id: uuid.UUID,
) -> uuid.UUID:
    """
    Generate a one-shot reset token, persist its bcrypt hash, return the row id.

    The plaintext token is returned to the caller (the HTTP route) only so
    Phase 6 PR #18 can plug an email sender in front of this service. The
    current router discards it after logging — see api/v1/admin/users.py.

    Returns the new ``password_reset_tokens.id``. The plaintext is NOT
    returned: this service is responsible for hashing + persisting and the
    route is responsible for the side-channel delivery.
    """
    user = await _load_user_with_memberships(session, user_id)
    now = _now()

    # Single-pending-token policy: invalidate any prior live tokens for this
    # user before issuing a new one. We pull rows and mutate so the audit
    # listener captures each invalidation.
    live = (
        (
            await session.execute(
                select(PasswordResetToken).where(
                    PasswordResetToken.user_id == user_id,
                    PasswordResetToken.used_at.is_(None),
                    PasswordResetToken.invalidated_at.is_(None),
                    PasswordResetToken.expires_at > now,
                )
            )
        )
        .scalars()
        .all()
    )
    for prior in live:
        prior.invalidated_at = now

    plaintext = secrets.token_urlsafe(32)
    token_hash = hash_password(plaintext)
    row = PasswordResetToken(
        user_id=user.id,
        token_hash=token_hash,
        expires_at=now + _PASSWORD_RESET_TTL,
    )
    session.add(row)
    await session.commit()
    await session.refresh(row)

    log.info(
        "admin.user.password_reset_initiated",
        actor_id=str(actor.id),
        target_user_id=str(user_id),
        reset_token_id=str(row.id),
        invalidated_count=len(live),
    )

    # Plaintext is intentionally never returned. The model's id is enough
    # for the route to log + emit the audit event.
    del plaintext  # explicit drop — make the discard intent obvious
    return row.id


__all__ = [
    "AdminUserError",
    "AdminUserNotFound",
    "CannotModifySelf",
    "InvalidRoleAssignment",
    "LastSuperAdminProtected",
    "activate_user",
    "deactivate_user",
    "get_user_detail",
    "initiate_password_reset",
    "list_users",
    "update_user_role",
]
